### ISSUE TITLE
Change the exp name just by clicking on the name in column

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2055] opened 2022-07-18 18:55 UTC
This is a kinda fast way to help users to have custom information about the experiment. Please let’s discuss this idea. Thanks

Note: we finally will remove the plots toggle on the name and will use just a circle to toggle plots.

**Comment by shcheklein** [comment] 2022-07-18 23:58
Good idea. The problem is that names are provided and stored in DVC. @dberenbaum @pmrowla is there a way to change them after / where do we store them now?

**Comment by shcheklein** [comment] 2022-07-18 23:59
> Note: we finally will remove the plots toggle on the name and will use just a circle to toggle plots.

Not a big fan of this, since circles are too small. So if we do this - it will be a trade off.

**Comment by maxagin** [comment] 2022-07-19 00:18
> Note: we finally will remove the plots toggle on the name and will use just a circle to toggle plots.

>> Not a big fan of this, since circles are too small. So if we do this - it will be a trade off.

I really hope we will be able to move forward with the standard eye concept. Which to my mind is the most user-friendly solution.

**Comment by shcheklein** [comment] 2022-07-19 00:19
>  to move forward with the standard eye concept.

yes, it's not that easy to implement + it will be taking even more space (eyes, checkboxes, stars) + you are biased a bit - when I talk to people who do not come from design that sometimes are not that familia with this concept

**Comment by maxagin** [comment] 2022-07-19 00:32
> when I talk to people who do not come from design that sometimes are not that familia with this concept

I am parry:

<img width="299" alt="Screen Shot 2022-07-18 at 8 27 58 PM" src="https://user-images.githubusercontent.com/98249521/179638921-d9983ca1-acaf-4153-a64e-2eca963e89a9.png">

The icons width 18x18px. It looks very compact I think.

<img width="461" alt="Screen Shot 2022-07-18 at 8 30 09 PM" src="https://user-images.githubusercontent.com/98249521/179639024-96ea5201-3347-4d76-87d9-b4b99f049383.png">

**Comment by shcheklein** [comment] 2022-07-19 00:34
@maxagin trust me, I've seen this :) And trust me I still had some feedback that an eye icon is not that clear.

**Comment by maxagin** [comment] 2022-07-19 00:45
Good @shcheklein . We are going to make sure to guide the user ("Explain that circle triggering plots"), even using current circles. The same will work for the eye (if we will decide to have it). So I think that the icon is less important.

Regarding the:

>The problem is that names are provided and stored in DVC. @dberenbaum @pmrowla

We could hide the name without modifying it, and display a sort of "description" field visually same as the title. Keeping always the DVC name + a new editable field. Just thinking in loud. WDYT?

**Comment by shcheklein** [comment] 2022-07-19 01:20
We should try to avoid having too different layouts / names between the extension and the `dvc exp show`. If I see the names I kinda expect to have them in CLI as well.

**Comment by maxagin** [comment] 2022-07-19 03:46
> If I see the names I kinda expect to have them in CLI as well.

Sure. EXP description - a new field for CLI. It is just for GUI will appear instead of the title. WDYT?

**Comment by shcheklein** [comment] 2022-07-19 04:09
> Sure. EXP description - a new field for CLI.

I'm not sure I understand this tbh.

**Comment by dberenbaum** [comment] 2022-07-19 14:49
> Good idea. The problem is that names are provided and stored in DVC. @dberenbaum @pmrowla is there a way to change them after / where do we store them now?

There's no existing command (see https://github.com/iterative/dvc/issues/6667), but I think it would be helpful, and I doubt it's hard to implement since it should be possible by adding/removing git refs. cc @karajan1001

**Comment by karajan1001** [comment] 2022-07-21 08:17
> > Good idea. The problem is that names are provided and stored in DVC. @dberenbaum @pmrowla is there a way to change them after / where do we store them now?
> 
> There's no existing command (see [iterative/dvc#6667](https://github.com/iterative/dvc/issues/6667)), but I think it would be helpful, and I doubt it's hard to implement since it should be possible by adding/removing git refs. cc @karajan1001

I think it's not very hard to implement, but still need some time to finish it.

**Comment by shcheklein** [comment] 2022-10-16 18:39
Closing this in favor of #2457

**Closed by shcheklein** 2022-10-16 18:39 UTC
Labels: enhancement, A: table, DVC-first
