### ISSUE TITLE
The "Apply to Workspace" button makes it too easy to lose work in progress

### ISSUE THREAD

**Issue by djsauble** [iterative/vscode-dvc#4802] opened 2023-10-10 23:34 UTC
I tried out the DVC VSCode extension for the first time. After running an experiment a few times, I noticed the "Apply to workspace" button next to each experiment in the DVC sidebar.

After I clicked this button, I immediately lost all unstaged changes in my working directory. I had to set up a virtual environment again, reinstall my pip packages, and recreate the file containing the model code that was used for training.

This behavior is very counter-intuitive to me. I assumed that clicking this button would restore my working directory to the state at which the experiment was run, but instead it did a hard reset of my working directory.

When the user takes an action that potentially results in lost work, we should display a confirmation dialog that warns them.

Here's a video demonstrating what happened (the "click" happens at 0:09, and things start going bad at 0:24)

https://drive.google.com/file/d/1q8QTzizze21Ublg5HO4ukTLxXdWBDT52/view?usp=sharing

**Comment by mattseddon** [comment] 2023-10-11 00:18
What version of DVC are you using?

**Comment by djsauble** [comment] 2023-10-11 00:19
3.25.0

<img width="629" alt="image" src="https://github.com/iterative/vscode-dvc/assets/186715/1f6407ee-b3d4-440a-a254-8db628711b1f">

**Comment by mattseddon** [comment] 2023-10-11 00:22
Apply should not do this by default. It should actually fail. I thought this was fixed in https://github.com/iterative/dvc/pull/9992 but that change may have caused a regression. 

cc @dberenbaum

**Comment by mattseddon** [comment] 2023-10-11 00:29
Does this behave the same way if you have committed your `.gitignore`, `dvc.yaml`, etc?

**Comment by djsauble** [comment] 2023-10-11 00:35
It behaves as I expect after those files have been committed.

**Comment by mattseddon** [comment] 2023-10-11 05:14
I am pretty sure that this issue is caused by an edge case not handled by DVC. 

@dberenbaum should we try and handle this in the CLI or put some guard rails in in the extension? An example of handling this in the extension would be something along the lines of "prompt the user to commit if we ever detect a newly added `dvc.yaml`". This could lead to prompts being shown in error and sounds a lot more like a hack than fixing in the CLI. LMK what you think.

**Comment by shcheklein** [comment] 2023-10-24 21:16
@dberenbaum hey, should we move this / do this on DVC side?

**Comment by shcheklein** [comment] 2023-10-31 22:04
@dberenbaum what it's your take :)

**Comment by dberenbaum** [comment] 2023-10-31 23:54
@djsauble At 0:24 there is a message that something went wrong. Are you able to get back to that state and click on it so we can see what exactly went wrong? I'm not sure whether this is expected or not currently, and I need to go back and recall what we do with untracked files. Were any of these files tracked or git-ignored before you clicked apply?

In general, `dvc exp apply` does force overwrite files by default. However, it's also possible to revert that operation: https://dvc.org/doc/command-reference/exp/apply#expand-for-details-on-reverting-object-object. One step VS Code could take is to put this info somewhere for cases like this.

**Comment by dberenbaum** [comment] 2023-10-31 23:56
cc @pmrowla

**Comment by dberenbaum** [comment] 2023-11-01 00:46
`dvc exp apply` has gone through several iterations and lots of discussions around this topic, but I think the latest expected behavior is implemented and explained in https://github.com/iterative/dvc/pull/8994. According to that, files that aren't part of the experiment shouldn't be touched, so it looks like there is a bug in this case. I'm not quite sure how to reproduce this behavior, though. It looks like even the `.dvc` directory is lost, and I'm not sure how that could happen 😅 .

**Comment by pmrowla** [comment] 2023-11-01 06:41
I think this should already be fixed in the latest DVC release (after https://github.com/iterative/dvc/pull/10051 which reworked https://github.com/iterative/dvc/pull/9992)

**Comment by djsauble** [comment] 2023-11-03 16:57
I can't reproduce this, even on the original version of DVC (3.25.0) and the DVC VSCode extension (1.1.7).

1. I wiped my repository (including the .git folder)
2. I used the VSCode DVC extension to initialize git, initialize dvc, and create the first commit.
3. I added my train.py and dvc.yaml and ran a few experiments without committing these files or the results to git.
4. I clicked the "Apply to Workspace" button on one of the experiments, and my working directory was NOT wiped as I observed initially.

So I guess we can close this one. I'll let you know if I see it pop again.

**Closed** 2023-11-03 17:09 UTC
Labels: triage, A: onboarding
