### ISSUE TITLE
DVC CLI setup page is stuck on the same state after Python extension is installed

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#4248] opened 2023-07-10 18:42 UTC
We recommend to install the Python extension. After I'd done that I still saw the same message on the screen and disabled buttons. Can we detect the change?

**Comment by julieg18** [comment] 2023-07-10 22:18
Working on my end. 

* What OS are you on?
* Are you seeing any errors in the developer tools console or the DVC output?

Probably unrelated, but are you in a folder that had a python virtual env but is now deleted? I once had an issue with the Python Extension not clearing my cache correctly (thus breaking DVC Setup) and I had to run the `Python: Clear Cache and Reload Window` command to fix things.

**Comment by shcheklein** [comment] 2023-07-10 22:22
It's Windows.

> Are you seeing any errors in the developer tools console or the DVC output?

I can check it the next time.

> Probably unrelated, but are you in a folder that had a python virtual env but is now deleted? 

It's all conda envs on that machine.

> Python Extension not clearing my cache correctly 

I just installed it on it for the very first time. Not sure it's relevant tbh.

**Comment by julieg18** [comment] 2023-07-12 23:59
Tried testing on windows with a fresh install but can't reproduce. Going to close this for now since it's not reproducible and, as discussed synchronously,it possibly has something to do with windows dropping Python extension events.

**Closed by julieg18** 2023-07-12 23:59 UTC
Labels: bug, priority-p1, A: onboarding
