### ISSUE TITLE
`smooth` plots template broken

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#3130] opened 2023-01-20 20:37 UTC
The `smooth` plots template is broken and doesn't seem to account for the groupby, instead collapsing everything into one line.

To reproduce, you can use https://github.com/iterative/example-get-started and change the template in `dvc.yaml` for one of the linear plots to `smooth`:

```
$ git diff
diff --git a/dvc.yaml b/dvc.yaml
index 684eb69..9b34875 100644
--- a/dvc.yaml
+++ b/dvc.yaml
@@ -52,6 +52,7 @@ plots:
       y:
         eval/prc/train.json: precision
         eval/prc/test.json: precision
+      template: smooth
   - ROC:
       x: fpr
       y:
``` 

The smooth template is on the left below, and it should have two lines (the right plot also doesn't look great, but that should be fixable on the DVC side):

<img width="1125" alt="Screenshot 2023-01-20 at 3 31 23 PM" src="https://user-images.githubusercontent.com/2308172/213800463-7fdd36f1-a244-4c25-91ce-bd16be35eec4.png">

**Comment by shcheklein** [comment] 2023-01-21 19:58
I'm looking into this.

**Comment by shcheklein** [comment] 2023-01-22 00:02
The bug is on the `dvc-render` side, not VS Code:

https://user-images.githubusercontent.com/3659196/213894766-98b09aa9-d61e-460d-b552-7cb23004117a.mov

**Comment by shcheklein** [comment] 2023-01-22 00:05
Create a follow up ticket https://github.com/iterative/dvc-render/issues/110

**Comment by shcheklein** [comment] 2023-01-22 00:20
Okay, not clear yet. Reverting to here for now ...

**Comment by shcheklein** [comment] 2023-01-22 05:50
Should be fixed by https://github.com/iterative/dvc-render/pull/111

**Comment by shcheklein** [comment] 2023-01-24 22:59
Closed by https://github.com/iterative/dvc-render/pull/111

**Comment by dberenbaum** [comment] 2023-01-25 20:00
Thanks for looking into this.

I added a linear and smooth version of plots to https://github.com/iterative/vscode-dvc-demo to test.

![acc_linear](https://user-images.githubusercontent.com/2308172/214673897-800b5263-1145-4595-b5e6-ae9fe3955e7b.png)
![acc_smooth](https://user-images.githubusercontent.com/2308172/214673899-0748904e-9b61-4d51-b438-e0e84e25545d.png)

It's hard to tell because test and train lines are so close, but it looks pretty clear that there is no dashed line in the smooth plot.

Side note: For both plots, the legend suggests that the points will have different strokeDash properties, but I only see them in the lines, not the points. I'm not sure if it's not being set, or if it's invisible because the points are filled.

**Comment by shcheklein** [comment] 2023-01-27 00:18
I looked into this briefly, this a different issue now, and I'm looking into how it can be fixed.

The issue is that in certain cases extension modifies not only the template, but it also add an additional `filename::field` value into the datapoints, e.g.:

```json
{
        "step": "17",
        "train/acc": "0.7494666666666666",
        "dvc_inferred_y_value": "0.7494666666666666",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      }
```

It means that `groupby` by filename is not enough, we need to pass more. And it becomes a mess and unscalable. We need to go back to the drawing board and see if Vega template modifications on the extension side could be reduced. E.g. can we avoid touching data points at least.

This is now (for now) on us (vscode), not DVC renderer.

**Comment by dberenbaum** [comment] 2023-01-27 20:33
Can `filename` and `field` be kept separate? Do they need to be concatenated?

See also https://github.com/iterative/dvc-render/pull/111#issuecomment-1404220856 (asking why we only included `filename` and not `field` in that groupby).

**Comment by shcheklein** [comment] 2023-01-27 22:11
For now, they have to be concatenated, I'm looking into options to keep them apart. That's how the Vega template looks like in VS Code:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {
        "step": "0",
        "train/acc": "0.2707333333333333",
        "dvc_inferred_y_value": "0.2707333333333333",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "1",
        "train/acc": "0.40696666666666664",
        "dvc_inferred_y_value": "0.40696666666666664",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "2",
        "train/acc": "0.4991833333333333",
        "dvc_inferred_y_value": "0.4991833333333333",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "3",
        "train/acc": "0.6582666666666667",
        "dvc_inferred_y_value": "0.6582666666666667",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "4",
        "train/acc": "0.5437333333333333",
        "dvc_inferred_y_value": "0.5437333333333333",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "5",
        "train/acc": "0.6674",
        "dvc_inferred_y_value": "0.6674",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "6",
        "train/acc": "0.6644",
        "dvc_inferred_y_value": "0.6644",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "7",
        "train/acc": "0.6833166666666667",
        "dvc_inferred_y_value": "0.6833166666666667",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "8",
        "train/acc": "0.7272",
        "dvc_inferred_y_value": "0.7272",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "9",
        "train/acc": "0.68985",
        "dvc_inferred_y_value": "0.68985",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "10",
        "train/acc": "0.7435333333333334",
        "dvc_inferred_y_value": "0.7435333333333334",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "11",
        "train/acc": "0.6868166666666666",
        "dvc_inferred_y_value": "0.6868166666666666",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "12",
        "train/acc": "0.76165",
        "dvc_inferred_y_value": "0.76165",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "13",
        "train/acc": "0.7097833333333333",
        "dvc_inferred_y_value": "0.7097833333333333",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "14",
        "train/acc": "0.7694",
        "dvc_inferred_y_value": "0.7694",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "15",
        "train/acc": "0.7323666666666667",
        "dvc_inferred_y_value": "0.7323666666666667",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "16",
        "train/acc": "0.7824166666666666",
        "dvc_inferred_y_value": "0.7824166666666666",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "17",
        "train/acc": "0.7494666666666666",
        "dvc_inferred_y_value": "0.7494666666666666",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "18",
        "train/acc": "0.7894",
        "dvc_inferred_y_value": "0.7894",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "19",
        "train/acc": "0.7608166666666667",
        "dvc_inferred_y_value": "0.7608166666666667",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/train/acc.tsv",
          "field": "train/acc"
        },
        "filename": "training/plots/metrics/train/acc.tsv",
        "field": "train/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/train/acc.tsv::train/acc"
      },
      {
        "step": "0",
        "test/acc": "0.3712",
        "dvc_inferred_y_value": "0.3712",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "1",
        "test/acc": "0.4104",
        "dvc_inferred_y_value": "0.4104",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "2",
        "test/acc": "0.6052",
        "dvc_inferred_y_value": "0.6052",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "3",
        "test/acc": "0.7678",
        "dvc_inferred_y_value": "0.7678",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "4",
        "test/acc": "0.6457",
        "dvc_inferred_y_value": "0.6457",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "5",
        "test/acc": "0.7654",
        "dvc_inferred_y_value": "0.7654",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "6",
        "test/acc": "0.7689",
        "dvc_inferred_y_value": "0.7689",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "7",
        "test/acc": "0.7841",
        "dvc_inferred_y_value": "0.7841",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "8",
        "test/acc": "0.8325",
        "dvc_inferred_y_value": "0.8325",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "9",
        "test/acc": "0.7935",
        "dvc_inferred_y_value": "0.7935",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "10",
        "test/acc": "0.8514",
        "dvc_inferred_y_value": "0.8514",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "11",
        "test/acc": "0.791",
        "dvc_inferred_y_value": "0.791",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "12",
        "test/acc": "0.8712",
        "dvc_inferred_y_value": "0.8712",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "13",
        "test/acc": "0.8105",
        "dvc_inferred_y_value": "0.8105",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "14",
        "test/acc": "0.8735",
        "dvc_inferred_y_value": "0.8735",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "15",
        "test/acc": "0.8332",
        "dvc_inferred_y_value": "0.8332",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "16",
        "test/acc": "0.8862",
        "dvc_inferred_y_value": "0.8862",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "17",
        "test/acc": "0.8529",
        "dvc_inferred_y_value": "0.8529",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "18",
        "test/acc": "0.8929",
        "dvc_inferred_y_value": "0.8929",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      },
      {
        "step": "19",
        "test/acc": "0.8662",
        "dvc_inferred_y_value": "0.8662",
        "dvc_data_version_info": {
          "filename": "training/plots/metrics/test/acc.tsv",
          "field": "test/acc"
        },
        "filename": "training/plots/metrics/test/acc.tsv",
        "field": "test/acc",
        "rev": "workspace",
        "filename::field": "training/plots/metrics/test/acc.tsv::test/acc"
      }
    ]
  },
  "title": "dvc.yaml::Accuracy",
  "width": 300,
  "height": 300,
  "params": [
    {
      "name": "smooth",
      "value": 0.2,
      "bind": {
        "input": "range",
        "min": 0.001,
        "max": 1,
        "step": 0.01
      }
    }
  ],
  "transform": [
    {
      "loess": "dvc_inferred_y_value",
      "on": "step",
      "groupby": [
        "rev",
        "filename",
        "field",
        "filename::field"
      ],
      "bandwidth": {
        "signal": "smooth"
      }
    }
  ],
  "layer": [
    {
      "encoding": {
        "x": {
          "field": "step",
          "type": "quantitative",
          "title": "step"
        },
        "y": {
          "field": "dvc_inferred_y_value",
          "type": "quantitative",
          "title": "accuracy",
          "scale": {
            "zero": false
          }
        },
        "color": {
          "field": "rev",
          "type": "nominal"
        }
      },
      "layer": [
        {
          "mark": {
            "type": "line",
            "point": true,
            "tooltip": {
              "content": "data"
            }
          }
        }
      ]
    }
  ],
  
  "encoding": {
    "color": {
      "legend": {
        "disable": true
      },
      "field": "rev",
      "scale": {
        "domain": [
          "workspace"
        ],
        "range": [
          "#13adc7"
        ]
      }
    },
    "strokeDash": {
      
      "field": "filename::field",
      "scale": {
        "domain": [
          "training/plots/metrics/test/acc.tsv::test/acc",
          "training/plots/metrics/train/acc.tsv::train/acc"
        ],
        "range": [
          [
            1,
            0
          ],
          [
            8,
            8
          ]
        ]
      },
      "legend": {
        "disable": true
      }
    }
  }
}
```

(I modified and put `filename::field` into groupby to make it work).

VS Code adds this section (besides modifying the data points a bit with an additional field `filename::field`):

```json
"encoding": {
    "color": {
      "legend": {
        "disable": true
      },
      "field": "rev",
      "scale": {
        "domain": [
          "workspace"
        ],
        "range": [
          "#13adc7"
        ]
      }
    },
    "strokeDash": {
      
      "field": "filename::field",
      "scale": {
        "domain": [
          "training/plots/metrics/test/acc.tsv::test/acc",
          "training/plots/metrics/train/acc.tsv::train/acc"
        ],
        "range": [
          [
            1,
            0
          ],
          [
            8,
            8
          ]
        ]
      },
      "legend": {
        "disable": true
      }
    }
  }
```

This section is needed to:

- disable the legend (it'a available only if you zoom in) + side panel and the ribbon serve as a basic legend
- enforce a specific color per revision
- enforce a specific type of "dash" per filename + field

I can't easily at the moment come up with an alternative, but I'm pretty sure we can do something here. I don't like that we have to grow the list of things that go through group by. And unfortunately, it seems we can't group by by the whole `dvc_data_version_info` object :(

**Comment by dberenbaum** [comment] 2023-01-27 23:14
> * enforce a specific type of "dash" per filename + field

Do you know why is this important? I'm struggling to think where it could cause issues, and it would simplify things to not have to specify the domain of that field.

**Comment by shcheklein** [comment] 2023-01-27 23:22
> Do you know why is this important? I'm struggling to think where it could cause issues, and it would simplify things to not have to specify the domain of that field

Do you mean if we can keep it only `filename` in all case in the `domain` or not?

**Comment by dberenbaum** [comment] 2023-01-28 01:22
I meant if we could get rid of the `domain` field here:

```diff
    "strokeDash": {
      
      "field": "filename::field",
      "scale": {
-        "domain": [
-          "training/plots/metrics/test/acc.tsv::test/acc",
-          "training/plots/metrics/train/acc.tsv::train/acc"
-        ],
```

---

Some thoughts on what we could improve on the DVC side:
* Introduce a `group_id` field that equates to `filename::field` but can grow if needed (though I doubt we will need to add more dimensions at this point -- it seems like it would become way too complicated).
* Move all these fields to the top level and see if we can incorporate the `strokeDash` grouping on the DVC side.
* Make the output formats match with and without `--json`.

I don't think any of it would be too hard now that I have dug through the plots, so let me know what you think.

**Comment by dberenbaum** [comment] 2023-01-28 13:05
There's a rough POC of the ideas above in https://github.com/iterative/dvc/tree/plots-fields and https://github.com/iterative/dvc-render/tree/plots-fields. 

These changes updates output to include these new fields:

    ```json
    "dvc_id": "workspace::train/acc.tsv::train/acc",
    "dvc_rev": "workspace",
    "dvc_filename": "train/acc.tsv",
    "dvc_field": "train/acc",
    "dvc_source": "train/acc.tsv::train/acc"
    ```

* Incorporates these into templates, using `dvc_rev` for `color` and `dvc_source` for `strokeDash`.
* Drops `data_version_info`.

Here's an example of `dvc plots diff --split --json` output:

```json
{
  "dvc.yaml::Accuracy": [
    {
      "type": "vega",
      "revisions": [
        "HEAD",
        "workspace"
      ],
      "content": {
        "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
        "data": {
          "values": "<DVC_METRIC_DATA>"
        },
        "title": "dvc.yaml::Accuracy",
        "width": 300,
        "height": 300,
        "params": [
          {
            "name": "smooth",
            "value": 0.001,
            "bind": {
              "input": "range",
              "min": 0.001,
              "max": 1,
              "step": 0.001
            }
          }
        ],
        "layer": [
          {
            "mark": "line",
            "encoding": {
              "x": {
                "field": "step",
                "type": "quantitative",
                "title": "step"
              },
              "y": {
                "field": "dvc_inferred_y_value",
                "type": "quantitative",
                "title": "accuracy",
                "scale": {
                  "zero": false
                }
              },
              "color": {
                "field": "dvc_rev",
                "type": "nominal"
              },
              "strokeDash": {
                "field": "dvc_source",
                "type": "nominal"
              }
            },
            "transform": [
              {
                "loess": "dvc_inferred_y_value",
                "on": "step",
                "groupby": [
                  "dvc_rev",
                  "dvc_source"
                ],
                "bandwidth": {
                  "signal": "smooth"
                }
              }
            ]
          },
          {
            "mark": {
              "type": "point",
              "tooltip": {
                "content": "data"
              }
            },
            "encoding": {
              "x": {
                "field": "step",
                "type": "quantitative",
                "title": "step"
              },
              "y": {
                "field": "dvc_inferred_y_value",
                "type": "quantitative",
                "title": "accuracy",
                "scale": {
                  "zero": false
                }
              },
              "color": {
                "field": "dvc_rev",
                "type": "nominal"
              },
              "strokeDash": {
                "field": "dvc_source",
                "type": "nominal"
              }
            }
          }
        ]
      },
      "datapoints": {
        "workspace": [
          {
            "step": "0",
            "train/acc": "0.5262",
            "dvc_inferred_y_value": "0.5262",
            "rev": "workspace::train/acc.tsv::train/acc",
            "dvc_id": "workspace::train/acc.tsv::train/acc",
            "dvc_rev": "workspace",
            "dvc_filename": "train/acc.tsv",
            "dvc_field": "train/acc",
            "dvc_source": "train/acc.tsv::train/acc"
          },
...
```

**Comment by shcheklein** [comment] 2023-02-05 00:24
Should be fixed by the latest update by @dberenbaum in `dvc-render`.

**Closed by shcheklein** 2023-02-05 00:24 UTC
Labels: priority-p1, A: plots
