### ISSUE TITLE
Context menu improvements

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2039] opened 2022-07-15 03:35 UTC
- [ ] The context menu should be displayed on the right side of the cursor. Currently, it's being displayed at the bottom/center
- [ ] Remove the arrow from the context-menu component and I would suggest removing it from other tooltips also, it is kind of old practice.

The context menu is usually placed on the right/bottom side of the mouse click unless it is close to the right age of the screen, then it will appear on the left side. However, in VSCode it seems like always on the right side, but we can do it correctly I think.

Example:

https://user-images.githubusercontent.com/98249521/179145699-431d66d9-90e3-490f-9e3d-a33ec60c2a03.mov

**Comment by mattseddon** [comment] 2022-09-07 20:10
Duplicate of two tasks in #2241

**Closed by mattseddon** 2022-09-07 20:10 UTC
Labels: bug, priority-p2, A: table, size: S

**Comment by maxagin** [comment] 2022-09-08 00:31
> Duplicate of two tasks in https://github.com/iterative/vscode-dvc/issues/2241

Yeah... Almost two months old ticket.
