### ISSUE TITLE
After installing the update EXP broken

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2109] opened 2022-07-27 04:23 UTC
Run EXP - Click to install an update - The EXP is still running, already around 2h. 
Or we stop processes or continue from the point where it's stopped.
Do not know what to do now.

https://user-images.githubusercontent.com/98249521/181160934-2031b394-40af-4f8c-82f8-5bd140588901.mov

**Comment by mattseddon** [comment] 2022-07-27 05:35
The cause is probably https://github.com/iterative/dvc/issues/8031.

I recommend downgrading.

**Comment by maxagin** [comment] 2022-07-27 17:18
Good. Just wanted to mention this. I know I am not a typical user, but sill :) Bay the way it is still running. 14h :)

**Comment by mattseddon** [comment] 2022-07-27 21:22
It won't ever finish you need to run `dvc exp gc -f --all-tags` and delete `.dvc/tmp/exps`, the data is corrupted and the extension isn't actually running anything.

**Comment by mattseddon** [comment] 2022-07-27 23:33
Sorry, issue was probably https://github.com/iterative/dvc/issues/8045. I linked the wrong one.

**Comment by shcheklein** [comment] 2022-07-27 23:34
@maxagin can you update the DVC version (install the development one?) It should be fixed there. Otherwise, advice is yes - cleanup `.dvc/tmp/exps` and lock files (`.dvc/tmp/*lock*`).

**Closed by shcheklein** 2022-07-27 23:34 UTC
Labels: bug, A: side-panel
