### ISSUE TITLE
`exp show`: performance issues

### ISSUE THREAD

**Issue by mattseddon** [iterative/vscode-dvc#1690] opened 2022-05-10 23:59 UTC
When running a checkpoint based experiment with 200 epochs (in the workspace) `exp show --no-fetch --show-json` can take ~2m to return. 

The command seemed to max out at `138696ms` run time. Run time drops after the experiment run has been completed to ~1m.

Repository: demo project in this repo. 

Note: This is a toy project with only a handful of params/metrics/deps/outs. I suspect the performance would be worse for a real project.

Related to #828 and https://github.com/iterative/dvc/issues/7693

**Comment by shcheklein** [comment] 2022-07-26 20:51
Agreed with @pmrowla we should not be running `git gc` automatically. People might rely on Git default and being able to find things using reflog, etc. 

@pmrowla @mattseddon do you a sense what kind of objects is causing this? is it just amount of `exps`, or something else? Is there a way to to do something like `git optimize`? Just curious about the root cause of this. W/o better understanding it's hard to act here.

**Comment by shcheklein** [comment] 2022-11-13 02:09
Closing this. Let's first get to people complaining about this.

**Closed by shcheklein** 2022-11-13 02:09 UTC
Labels: A: table, A: integration, performance
