### ISSUE TITLE
DVC not detected automatically by the extension

### ISSUE THREAD

**Issue by alex000kim** [iterative/vscode-dvc#1955] opened 2022-06-28 12:39 UTC
When I used the extension via Codespaces, DVC isn't automatically detected and I need to set its path manually.
Two repos where I am seeing this:
- https://github.com/iterative/example-get-started
- https://github.com/iterative/magnetic-tiles-defect

I suspect it might be because pip dependencies are installed directly into the user's python (instead of using venv). E.g.:
https://github.com/iterative/example-get-started/blob/main/.devcontainer/devcontainer.json#L7

**Comment by shcheklein** [comment] 2022-06-28 22:11
> In order to get this working out of the box I would add "dvc.dvcPath": "dvc" to the [VS Code specific settings](https://code.visualstudio.com/docs/remote/devcontainerjson-reference#_vs-code-specific-properties) in the devcontainer.json.

Q - why do we need this? Extension should be detecting any global installation by default, right? Also, it works for me as far as I remember w/o manually changing any settings (I specifically mean the `example-get-started` project in Codespaces)

**Comment by mattseddon** [comment] 2022-06-28 22:18
Ok, I have just tested `example-get-started` in Codespaces and it takes a long time to get going but works as intended for me:

![image](https://user-images.githubusercontent.com/37993418/176312361-b047c3ae-fc72-4ea4-96e5-69a929e463b4.png)

**Comment by mattseddon** [comment] 2022-06-29 01:18
Raised the above PR which should close this issue. There are other mitigation options but the above seems like the best for this particular scenario.

**Closed** 2022-06-29 01:47 UTC
Labels: bug, priority-p1, A: extension, A: codespaces

**Comment by alex000kim** [comment] 2022-06-29 02:06
This makes sense - I just wasn't setting up Codespaces containers properly. Thanks!

**Comment by shcheklein** [comment] 2022-06-29 02:20
What about the `example-get-started` repo? I think we are using the MS Python base image for it (probably it should include ms-python?), but it fails to detect it also (only Alex can reproduce this?) - should we also try to specify the `ms-python` explicitly?
